### ISSUE TITLE
The floating point conversion treats negative numbers as zero

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-optimade#120]
https://github.com/aiidateam/aiida-optimade/blob/99ee1113cfc109a40a83bb43af8d07ce7e1601e6/aiida_optimade/translators/structures.py#L124-L125

Is that intentional? Otherwise I'd suggest to compare against the absolute value.

Furthermore, considering all values below 1e-8 as zero is potentially not safe for specific applications.

**Comment by CasperWA** [comment]
It is loosely based on [these thresholds](https://github.com/aiidateam/aiida-core/blob/develop/aiida/orm/nodes/data/structure.py#L25-L31) and I would definitely consider all Ångstrøm values less than 1e-8 to be 0 for all intents and purposes.

Edit: Ah, didn't take into account the title here. Indeed, you are correct about negative numbers. This should be remedied.

**Comment by csadorf** [comment]
@CasperWA Do you want me to create a PR to fix this?
