### ISSUE TITLE
Provider-specific field included without prefix

### ISSUE THREAD

**Issue by ml-evs** [aiidateam/aiida-optimade#157]
Apologies if it is already known, but provider-specific fields are being served without the provider prefix from e.g. https://aiida-dev.materialscloud.org/optimade-sample/optimade/v1/structures. 

The custom `ctime` property is correctly displayed as `_mcloud_ctime` at the [`/info/structures/`](https://aiida-dev.materialscloud.org/optimade-sample/optimade/v1/info/structures) endpoint (and hence the python-tools validator looks for it) but it is provided  simply as `ctime` at the `/structures/` endpoint. 

This causes the python-tools validator to skip lots of tests, as it thinks it cannot trust the `response_fields` query parameter.

**Comment by CasperWA** [comment]
This is indeed known, but maybe what you've written here is a finer nuance than previously described (see #149).

**Comment by CasperWA** [comment]
Note to self: If `response_fields` is used, the provider-specific prefix is _not_ added to provider-specific fields. I.e., if one simply goes to the entry endpoint `/structures`, `ctime` shows up as either `_aiida_ctime` or `_mcloud_ctime` (depending on the implementation), while if `response_fields` is used, the prefix is not added and `ctime` is _always_ returned.

**Comment by ml-evs** [comment]
Huh, any idea why we don't run into this in the reference optimade-python-tools? Looking at the changes in the PR that closes this I would've thought we would have the same problem...

**Comment by CasperWA** [comment]
It's mainly due to the fact that I am extending the `StructureResourceAttributes` pydantic model to include provider-specific fields, adding a function for the configuration option `alias_generator`.

I don't think we are doing anything similar in the base OPTIMADE Python Tools.
