### ISSUE TITLE
[MaterialsCloud] OpenAPI (and all /extensions/*) not available

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-optimade#169]
The OpenAPI specification cannot be reached via https://aiida-dev.materialscloud.org/optimade-sample/optimade/v1/extensions/openapi.json
This _should_ be available as it is also listed as a valid endpoint in the `/info` endpoint.

**Comment by CasperWA** [comment]
I believe this has to do with the way FastAPI sets up the routes for these endpoints in combination with it running in a Docker.

**Comment by CasperWA** [comment]
See the [FastAPI documentation](https://fastapi.tiangolo.com/advanced/behind-a-proxy) on `root_path`.

**Comment by unkcpz** [comment]
closed by #361
