### ISSUE TITLE
automatic pagination?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-optimade#25]
hi @CasperWA 
I'm in the process of setting up some automatic monitoring of the optimade servers on materials cloud to make sure that they are up.

While doing so, I realized that the default response to
https://dev-aiida-dev.materialscloud.org/optimade-sample/optimade/structures
is ~2MB in size.

Would it perhaps make sense to adjust the default pagination in such a way that the default response does not exceed 100KB?

**Comment by CasperWA** [comment]
Sure. This can be set in the `config.json` file [here](https://github.com/aiidateam/aiida-optimade/blob/12d223757343b20037e4011457919c9a811b5d77/aiida_optimade/config.json#L3).
The next variable `"db_page_limit"` is the total number of results that is allowed by the DB backend (when using the query parameter `page_limit=<some-integer-value>`.

**Comment by CasperWA** [comment]
This has been solved by lowering the default `page_limit` to 15 and introducing a `page_limit_max` in `aiida-optimade` as well as "upstream" in [`optimade-python-tools`](https://github.com/Materials-Consortia/optimade-python-tools).
