### ISSUE TITLE
Some anonymous chemical formulae are not reduced

### ISSUE THREAD

**Issue by ml-evs** [aiidateam/aiida-optimade#279]
Just spotted this in e.g. https://aiida.materialscloud.org/2dstructures/optimade/v1/structures/11, which has `chemical_formula_anonymous` of "A12B6". There's also several examples on the first page of results for https://aiida.materialscloud.org/optimade-sample/optimade/v1/structures?response_fields=chemical_formula_anonymous.

This is not something that is currently validated by optimade-python-tools for this field or for `chemical_formula_reduced` (I will raise an issue).

**Comment by CasperWA** [comment]
Right. So the point here is that it should not be `A12B6`, but `A2B1`? Or maybe even `A2B`? It's the largest species first, right?

**Comment by ml-evs** [comment]
`A2B`, aye

**Comment by ml-evs** [comment]
Something a bit funny here too: https://aiida.materialscloud.org/optimade-sample/optimade/v1/structures/17, where 
`chemical_formula_anonymous` is "A44B15C9D4E3F2GHI0J0K0L0".

**Comment by CasperWA** [comment]
True. `0` shouldn't exist.
