### ISSUE TITLE
Drop python 3.8 support

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-optimade#499]
Hi @CasperWA

It would be great to have #484 and #482 merged.

Currently they're failing because both aiida-core v2.4.0 and optimade-python-tools 0.25 are not compatible with 3.8 any more. 

Any pointers on best way to do this? I see that the readme table will need a bit of an overhaul.

**Comment by CasperWA** [comment]
Right. Yeah, it would need an overhaul on the readme table - that's quite straightforward, but at the same time a bit complicated 😅. Then it'd need a new version where Python 3.8 support is dropped. I'd suggest doing that through first having a PR that removes Python 3.8 support in the metadata of the setup information, and then runs `pyupgrade` with `--py37-plus` on the whole repo, and then ensure all CI jobs and pre-commit hooks run with Python 3.9.
Once that has been updated in `master`, a new release can be made (this is all assuming the readme has been updated accordingly as well). I'd suggest a new minor release.
