### ISSUE TITLE
Also use CifData

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-optimade#9]
Make it possible to also show `CifData` nodes in the `/structures` endpoint.

**Comment by CasperWA** [comment]
Calling @ltalirz for some advice here.

The implementation designs I have considered are these:

1. Convert a `CifData` to a `StructureData` (in-memory), use the already in-place translator to calculate/determine the OPTIMADE fields, store them (as is done for `StructureData`) in the original `CifData` node's extras - done.
 
or

2. Create new translator for each OPTIMADE field, use the information available from a `CifData` to calculate/determine these, finally store as usual in the node's extras.

I am wondering whether the second is even possible? How would I retrieve the information about kinds and sites - wouldn't it just be the same way the conversion from `CifData` to `StructureData` is done? So then why not just go with option 1?
Are there information lost in the conversion from `CifData` to `StructureData`? In that case option 2 would be preferable.

**Comment by ltalirz** [comment]
> I am wondering whether the second is even possible? How would I retrieve the information about kinds and sites 

Why don't you write to @merkys  ask how they do it - they must already have a solution for this.

To me, 2. is the preferable option, since the CifData contains richer information.
In the meanwhile, 1. can also be a simple & workable solution.

**Comment by CasperWA** [comment]
Added in #183.

**Comment by CasperWA** [comment]
Added in #183.
